version: '3'
services:
  backend:
    container_name: "ydown_backend"
    build: .
    restart: always
    ports:
      - 3001:3001
    networks:
      - backend
    environment:
      - MONGODB_URI="mongodb://mongodb"
      - COOKIE_SECRET="goose"
      - YTDL_NO_UPDATE=true
      - TZ=Australia/Sydney
    volumes:
      - ./persist:/persist
  mongodb:
    image: mongo
    container_name: "ydown_mongodb"
    networks:
      - backend
    volumes:
      - ./mongodb:/data/db

networks:
  backend:
    name: ydown_backend
